import { MasterSiteConfig } from "./config-schema";

export const DEFAULT_MASTER_CONFIG: MasterSiteConfig = {
  maintenanceSettings: {
    enabled: false,
    title: "WEBSITE TEMPORARILY UNAVAILABLE",
    message: "FashAI Universal is currently undergoing scheduled platform maintenance. Public access will resume shortly.",
    allowNavigation: false,
    allowEnquiryForms: false,
    allowRegistrations: false,
    allowApplications: false,
    allowGalleryInteraction: false,
    allowCTA: false,
  },
  globalSettings: {
    siteTitle: "FashAI Universal — International Luxury Fashion & Events Platform",
    metaTitle: "FashAI Universal — International Fashion & Events Platform",
    metaDescription: "FashAI Universal provides end-to-end event management, planning, and production for luxury fashion and lifestyle events across the UAE, India, and worldwide.",
    favicon: "/favicon.ico",
    ogImage: "/assets/brand/fashai-og-share.png",
    contactEmail: "contact@fashaiuniversal.com",
    instagramUrl: "https://www.instagram.com/fashai_universal",
    copyrightYear: "2026",
    defaultCtaText: "CONTACT US →",
    defaultCtaUrl: "/contact",
  },
  themeSettings: {
    light: {
      background: "#FFFFFF",
      primaryText: "#111111",
      secondaryText: "#333333",
      primaryAccent: "#F15E1C",
      secondaryAccent: "#D4AF37",
      softSurface: "#FAF8F5",
      border: "rgba(0, 0, 0, 0.1)",
    },
    dark: {
      background: "#050505",
      primaryText: "#FFFFFF",
      secondaryText: "#E0E0E0",
      primaryAccent: "#D4AF37",
      secondaryAccent: "#F15E1C",
      softSurface: "#0A0908",
      border: "rgba(255, 255, 255, 0.1)",
    },
  },
  typographySettings: {
    headingFont: "DM Serif Display, Didot, serif",
    bodyFont: "Jost, sans-serif",
    navigationFont: "Jost, sans-serif",
    headingScale: 1.0,
    bodyScale: 1.0,
    letterSpacing: "normal",
    lineHeight: "normal",
  },
  heroSettings: {
    title: "INTERNATIONAL FASHION & EVENTS PLATFORM",
    subtitle: "BRIDGING THE UAE, INDIA & GLOBAL THROUGH RUNWAY, CULTURE AND CREATIVE TALENT",
    eyebrow: "UAE · INDIA · GLOBAL",
    supportingText: "Connecting designers, talent, brands and audiences across international fashion hubs.",
    ctaText: "SEE UPCOMING",
    ctaUrl: "/upcoming",
    heroImage: "/assets/home/where_fashion_creates_possibilities.png",
    heroFallbackImage: "/assets/final/project-lifestyle-2025-hero.jpg",
    heroVideo: "",
    posterImage: "/assets/home/where_fashion_creates_possibilities.png",
    overlayOpacity: 0.3,
    brightness: 1.0,
    imagePosition: "center",
    videoAutoplay: true,
    videoLoop: true,
    videoMuted: true,
    mobileImage: "",
    mobileVideo: "",
    mobileFallback: "",
  },
  homepageSections: [
    { id: "hero", title: "Hero Block", enabled: true, order: 1 },
    { id: "who_we_are", title: "A Global Fashion Movement (Who We Are)", enabled: true, order: 2 },
    { id: "our_events", title: "Our Events Banner (LifeStyle & Runway)", enabled: true, order: 3 },
    { id: "intro_statement", title: "Platform Intro Statement", enabled: true, order: 4 },
    { id: "upcoming_event", title: "Upcoming Event (LifeStyle 2026)", enabled: true, order: 5 },
    { id: "what_we_do", title: "What We Do", enabled: true, order: 6 },
    { id: "designers_showcase", title: "Designer Participation & Showcase", enabled: true, order: 7 },
    { id: "disciplines", title: "Creative Disciplines", enabled: true, order: 8 },
    { id: "fashprism_stories", title: "FashPrism Stories & Editorial", enabled: true, order: 9 },
    { id: "open_nominations", title: "Open Nominations & Applications", enabled: true, order: 10 },
    { id: "instagram", title: "Instagram / Social Section", enabled: true, order: 11 },
    { id: "footer", title: "Haute Couture Footer", enabled: true, order: 12 },
  ],
  events: [
    {
      id: "lifestyle_2026",
      title: "LifeStyle 2026",
      category: "LIFESTYLE",
      description: "An international luxury fashion, lifestyle, and delegate summit connecting global creators, designers, and high-net-worth audiences.",
      location: "Dubai, United Arab Emirates",
      date: "TO BE ANNOUNCED",
      venue: "TO BE ANNOUNCED",
      status: "Registration Open",
      registrationStatus: "Open",
      sponsorshipStatus: "Open",
      dressCode: "Black Tie / Haute Couture",
      coverImage: "/assets/photos_more/lifestyle_banner.png",
      galleryImages: ["/assets/models/model_01.jpeg", "/assets/models/model_02.jpeg"],
      ctaText: "REGISTER INTEREST →",
      ctaUrl: "/contact",
      featured: true,
    },
    {
      id: "runway_2026",
      title: "Runway 2026",
      category: "RUNWAY",
      description: "Dedicated runway presentation formats for couture and ready-to-wear lines, bringing together global designers and buyers.",
      location: "India / UAE",
      date: "TO BE ANNOUNCED",
      venue: "TO BE ANNOUNCED",
      status: "Curation Open",
      registrationStatus: "Open",
      sponsorshipStatus: "Open",
      dressCode: "Couture Runway",
      coverImage: "/assets/photos_more/runway_banner.png",
      galleryImages: ["/assets/models/model_03.jpeg", "/assets/models/model_04.jpeg"],
      ctaText: "APPLY AS DESIGNER →",
      ctaUrl: "/apply/designer",
      featured: true,
    },
  ],
  servicesSettings: [
    {
      id: "fashion_events",
      name: "Fashion Events & Runway Management",
      category: "EVENTS",
      description: "High-impact runway productions, designer showcases, and couture salons.",
      status: "ACTIVE",
      disabledMessage: "Currently unavailable",
      ctaText: "EXPLORE EVENT FORMATS",
      ctaUrl: "/apply"
    },
    {
      id: "brand_shoots",
      name: "Brand Shoots & Commercial Visual Production",
      category: "CREATIVE PRODUCTION",
      description: "Commercial fashion shoots, campaign lookbooks, and high-fashion video production.",
      status: "ACTIVE",
      disabledMessage: "Temporarily paused",
      ctaText: "BOOK BRAND SHOOT",
      ctaUrl: "/contact"
    },
    {
      id: "digital_pr",
      name: "Digital PR & Global Promotions",
      category: "PROMOTION",
      description: "Multi-market digital exposure, media coverage, and high-fashion editorial features.",
      status: "ACTIVE",
      disabledMessage: "Currently unavailable",
      ctaText: "REQUEST DIGITAL PR",
      ctaUrl: "/contact"
    },
    {
      id: "event_management",
      name: "Event Management & Spatial Execution",
      category: "MANAGEMENT",
      description: "End-to-end event conceptualization, venue sourcing, spatial lighting, and delegate logistics.",
      status: "ACTIVE",
      disabledMessage: "Temporarily paused",
      ctaText: "ENQUIRE EVENT SERVICES",
      ctaUrl: "/contact"
    },
    {
      id: "talent_applications",
      name: "Talent Applications & Casting",
      category: "TALENT",
      description: "Global talent discovery, casting direction, and model/designer/stylist nominations.",
      status: "ACTIVE",
      disabledMessage: "Applications temporarily closed",
      ctaText: "APPLY AS TALENT",
      ctaUrl: "/apply"
    },
    {
      id: "corporate_it_events",
      name: "Corporate & IT Event Formats",
      category: "CORPORATE",
      description: "Executive summits, IT innovation launches, and corporate delegate experiences.",
      status: "ACTIVE",
      disabledMessage: "Currently unavailable",
      ctaText: "PLAN CORPORATE EVENT",
      ctaUrl: "/contact"
    }
  ],
  popupSettings: {
    enabled: true,
    eventId: "lifestyle_2026",
    title: "LifeStyle 2026 · Dubai",
    subtitle: "INTERNATIONAL FASHION & LIFESTYLE SUMMIT",
    backgroundImage: "/assets/photos_more/lifestyle_banner.png",
    overlayOpacity: 0.6,
    date: "TO BE ANNOUNCED",
    venue: "TO BE ANNOUNCED",
    dressCode: "Black Tie / Haute Couture",
    registrationCtaText: "REGISTER INTEREST →",
    sponsorshipCtaText: "SPONSORSHIP ENQUIRY →",
    registrationUrl: "/contact",
    sponsorshipUrl: "/contact",
    displayDelay: 3000,
    scrollTriggerPercentage: 30,
    showOncePerSession: true,
    showOncePerVisitor: false,
  },
  navigationSettings: [
    { id: "home", label: "HOME", href: "/", enabled: true, order: 1 },
    { id: "upcoming", label: "UPCOMING", href: "/upcoming", enabled: true, order: 2 },
    { id: "services", label: "SERVICES", href: "/services", enabled: true, order: 3 },
    { id: "projects", label: "PROJECTS", href: "/projects", enabled: true, order: 4 },
    { id: "blog", label: "BLOG", href: "/fashion-magazine", enabled: true, order: 5 },
  ],
  footerSettings: {
    brandName: "FashAI Universal",
    description: "Fashion, talent and experiences across Dubai, UAE & India.",
    instagramHandle: "@fashai_universal",
    instagramUrl: "https://www.instagram.com/fashai_universal",
    exploreLinks: [
      { label: "Home", href: "/", enabled: true },
      { label: "Upcoming", href: "/upcoming", enabled: true },
      { label: "Services", href: "/services", enabled: true },
      { label: "Gallery", href: "/gallery", enabled: true },
      { label: "Contact", href: "/contact", enabled: true },
    ],
    getInvolvedLinks: [
      { label: "Designer", href: "/apply/designer", enabled: true },
      { label: "Model", href: "/apply/model", enabled: true },
      { label: "Makeup Artist", href: "/apply/makeup-artist", enabled: true },
      { label: "Fashion Stylist", href: "/apply/fashion-stylist", enabled: true },
      { label: "Open Nominations", href: "/apply", enabled: true },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "/privacy", enabled: true },
      { label: "Terms & Conditions", href: "/terms", enabled: true },
    ],
    poweredByLogo: "/assets/brand/Final_Powered_by_logo.png",
  },
  applicationCategories: [
    { id: "designer", title: "Designer & Couture Atelier", description: "Present your creative work and runway showcase opportunities.", enabled: true, fields: [] },
    { id: "model", title: "Model & Runway Talent", description: "Participate in international runway and campaign productions.", enabled: true, fields: [] },
    { id: "makeup_artist", title: "Makeup & Beauty Artistry", description: "Backstage beauty direction and precision makeup direction.", enabled: true, fields: [] },
    { id: "fashion_stylist", title: "Fashion Stylist", description: "Wardrobe curation, campaign lookbooks and visual direction.", enabled: true, fields: [] },
    { id: "influencer", title: "Influencer / Content Creator", description: "Editorial coverage, digital partnerships and social features.", enabled: true, fields: [] },
    { id: "celebrity", title: "Celebrity & Public Figure", description: "VVIP delegate presence and brand ambassador features.", enabled: true, fields: [] },
    { id: "choreographer", title: "Choreographer", description: "Catwalk choreography and spatial runway presentation.", enabled: true, fields: [] },
    { id: "cstp", title: "CSTP Technical Specialist", description: "Couture, Spatial, Technology & Production specialists.", enabled: true, fields: [] },
    { id: "commentary", title: "Fashion Commentary & Media", description: "Journalism, editorial commentary and press coverage.", enabled: true, fields: [] },
  ],
  motionSettings: {
    globalAnimations: true,
    pageTransitions: true,
    scrollAnimations: true,
    hoverAnimations: true,
    backgroundMotion: true,
    customCursor: true,
    backgroundVideo: true,
    reducedMotionSafe: true,
  },
  pages: [
    { id: "home", route: "/", title: "FashAI Universal — Home", metaDescription: "International luxury fashion & events platform.", published: true, visibility: "PUBLIC" },
    { id: "upcoming", route: "/upcoming", title: "Upcoming Events · FashAI Universal", metaDescription: "Explore upcoming shows and chapters.", published: true, visibility: "PUBLIC" },
    { id: "gallery", route: "/gallery", title: "Gallery & Retrospective · FashAI Universal", metaDescription: "Visual archive of haute couture and stage presentations.", published: true, visibility: "PUBLIC" },
    { id: "apply", route: "/apply", title: "Talent Applications · FashAI Universal", metaDescription: "Submit applications for designers, models, and creators.", published: true, visibility: "PUBLIC" },
    { id: "contact", route: "/contact", title: "Contact & Registrations · FashAI Universal", metaDescription: "Get in touch for delegate registrations and partnerships.", published: true, visibility: "PUBLIC" },
    { id: "privacy", route: "/privacy", title: "Privacy Policy · FashAI Universal", metaDescription: "Official privacy policy and data governance.", published: true, visibility: "PUBLIC" },
    { id: "terms", route: "/terms", title: "Terms & Conditions · FashAI Universal", metaDescription: "Official terms and conditions.", published: true, visibility: "PUBLIC" },
  ],
  galleryItems: [
    { id: "gal_1", title: "Couture Silhouette", image: "/assets/final/project-lifestyle-2025-hero.jpg", category: "COUTURE DETAILS", caption: "High-precision garment tailoring", altText: "Couture details", published: true, featured: true, order: 1 },
    { id: "gal_2", title: "Runway Stage Dubai", image: "/assets/final/project-lifestyle-2025-01.jpg", category: "RUNWAY & STAGE", caption: "Spatial lighting and catwalk dynamics", altText: "Runway stage", published: true, featured: true, order: 2 },
    { id: "gal_3", title: "VIP Delegate Gathering", image: "/assets/final/project-lifestyle-2026-hero.jpg", category: "PEOPLE & MOMENTS", caption: "Delegate gathering at LifeStyle showcase", altText: "VIP delegates", published: true, featured: true, order: 3 },
    { id: "gal_4", title: "Architectural Lighting", image: "/assets/final/project-lifestyle-2025-02.jpg", category: "ARCHITECTURE & LIGHTING", caption: "Spatial lighting design", altText: "Architecture lighting", published: true, featured: true, order: 4 },
  ],
  mediaLibrary: [
    { id: "med_1", filename: "where_fashion_creates_possibilities.png", url: "/assets/home/where_fashion_creates_possibilities.png", type: "image", size: 450000, dimensions: "1200x800", altText: "OUR VISION", caption: "FashAI Universal Vision", category: "Home", tags: ["vision", "hero"], uploadedAt: "2026-09-24T12:00:00Z", usedIn: ["Hero", "Who We Are"] },
    { id: "med_2", filename: "lifestyle_banner.png", url: "/assets/photos_more/lifestyle_banner.png", type: "image", size: 620000, dimensions: "1600x900", altText: "LifeStyle 2026 Banner", caption: "LifeStyle Event Banner", category: "Events", tags: ["lifestyle", "banner"], uploadedAt: "2026-09-24T12:00:00Z", usedIn: ["Our Events", "LifeStyle 2026"] },
    { id: "med_3", filename: "runway_banner.png", url: "/assets/photos_more/runway_banner.png", type: "image", size: 580000, dimensions: "1600x900", altText: "Runway 2026 Banner", caption: "Runway Event Banner", category: "Events", tags: ["runway", "banner"], uploadedAt: "2026-09-24T12:00:00Z", usedIn: ["Our Events", "Runway 2026"] },
    { id: "med_4", filename: "fashai_logo_final.png", url: "/assets/brand/fashai_logo_final.png", type: "image", size: 900000, dimensions: "1263x1245", altText: "FashAI Universal Official Logo", caption: "Official Brand Logo", category: "Brand", tags: ["logo", "brand"], uploadedAt: "2026-09-26T00:00:00Z", usedIn: ["Header", "Footer", "MobileMenu"] },
  ],
  lastUpdated: new Date().toISOString(),
  lastMediaUpdate: new Date().toISOString(),
  isDraft: false,
};
